version: '3.7'
services:
  test:
    build: ./services/web
    command: python tests.py
    volumes:
      - ./services/web/:/usr/src/app/:z
    ports:
      - 5001:5001
    env_file:
      - ./.env.test

  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/:z
    restart: on-failure
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/:z
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: