version: '3.3'
services:
  test:
    build: ./services/web
    command: python tests.py
    volumes:
      - ./services/web/:/usr/src/app/:z
    ports:
      - 5001:5001
    env_file:
      - ./.env.test

  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/:z
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - elasticsearch
      - redis
    links:
      - redis:redis

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/:z
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    image: redis:6.0.5-alpine
    volumes:
      - redis_data:/var/lib/redis

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data: