version: 2
jobs:
  linter:
    docker:
      - image: python:3.8.1-slim-buster
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install linter
          command: pip install flake8
      - run:
          name: Run linter
          command: flake8 --ignore=E501,F401,E402,F841 .

  tests:
    machine:
      image: circleci/classic:201711-01
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Building services for test
          command: |
            make build-test
      - run:
          name: Run tests
          command: |
            make test-docker
workflows:
  version: 2
  lint_and_test:
    jobs:
      - linter:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - tests:
          requires:
            - linter
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/